from sqlalchemy import exists
from database import SessionLocal
from db_deck import DbDeck, add_db_deck
from deck import Deck
from redis_utils import rget_json, rlock, rset_json
from settings import BOT_DECK_USERNAME, COMMON_DECK_USERNAME


COMMON_DECKS = [
    {
        'name': 'Learn to play',
        'cards': [
            'Pabu',
            'Meelo',
            'Roku',
            'Hakoda',
            'Yung',
            'Momo',
            'Southern Raider',
            'Katara',
            'Badgermole',
            'Opal',
            'Yon Rha',
            'Zaheer',
            'Oogi',
            'Gran-Gran Kanna',
            'Korra',
            'Juicy',
            'Dragon Bird Spirit',
            'Tarrlok',
        ],
    },
    {
        'name': 'Healing Hands',
        'cards': [
            'Zuko',
            'Zuko',
            'Mother Kya',
            'Mother Kya',
            'Kya',
            'Kya',
            'Taqukaq',
            'Katara',
            'Katara',
            'Sokka',
            'Sokka',
            'Elder Katara',
            'Yagoda',
            'Ryu',
            'Unalaq',
            'Bato',
            'Gran-Gran Kanna',
            'Master Pakku',
        ]
    },
    {
        'name': 'Switcheroo',
        'cards': [
            'Monk Gyatso',
            'Monk Gyatso',
            'Ikki',
            'Lefty',
            'Momo',
            'Yangchen',
            'Bumi II',
            'Opal',
            'Opal',
            'Appa',
            'Jinora',
            'Tenzin',
            'Tenzin',
            'Tashi',
            'Tashi',
            'Aang',
            'Uncle Iroh',
            'Dragon Bird Spirit',
        ]
    },
    {
        'name': 'Attack and Defense',
        'cards': [
            'Iroh II',
            'Iroh II',
            'Combustion Man',
            'Pabu',
            'Tonraq',
            'Izumi',
            'Izumi',
            'Taqukaq',
            'Taqukaq',
            'Riley',
            'P\'li',
            'P\'li',
            'Senna',
            'Toph',
            'Fire Lord Sozin',
            'Mai',
            'Fire Lord Ozai',
            'Master Pakku',
        ],
    },
    {
        'name': 'The Card Advantage',
        'cards': [
            'Hiroshi',
            'Hiroshi',
            'Bum-Ju',
            'Bum-Ju',
            'Tsemo',
            'Kai',
            'Kai',
            'Cabbage Man',
            'La',
            'La',
            'The Big Bad Hippo',
            'The Big Bad Hippo',
            'Professor Zei',
            'Moon Spirit Yang',
            'Moon Spirit Yang',
            'The Boulder',
            'The Boulder',
            'King Bumi',
        ]
    },
    {
        'name': 'Naked Aggression',
        'cards': [
            'Combustion Man',
            'Combustion Man',
            'Meelo',
            'Iroh II',
            'Hakoda',
            'Hakoda',
            'Riley',
            'Man in the Mask',
            'Opal',
            'Yuyan Archers',
            'Ghazan',
            'June',
            'Admiral Zhao',
            'Admiral Zhao',
            'Uncle Iroh',
            'Fire Lord Ozai',
            'Kuruk',
            'Fire Lord Azulon',
        ]
    },
    {
        'name': 'Lock and Chain',
        'cards': [
            'Dai Li Agent',
            'Dai Li Agent',
            'Pabu',
            'Kuvira',
            'Mako',
            'Mako',
            'Kai',
            'La',
            'Roku',
            'Baatar Jr.',
            'Baatar Jr.',
            'Master Yu',
            'Mai',
            'Lin',
            'Lin',
            'Champion Ming',
            'Champion Ming',
            'Suyin',
        ]
    },
    {
        'name': 'Aegis of Power',
        'cards': [
            'Pabu',
            'Pabu',
            'Teo',
            'Tyro',
            'Tyro',
            'P\'li',
            'Man in the Mask',
            'Master Jeong Jeong',
            'Master Jeong Jeong',
            'Badgermole',
            'Navy Officer',
            'Canyon Guide',
            'Suki',
            'Suki',
            'Yon Rha',
            'Professor Zei',
            'Piandao',
            'Ran and Shaw',
        ]
    },
    {
        'name': 'Survival of the Fittest',
        'cards': [
            'Kelsang',
            'Kelsang',
            'Meelo',
            'Meelo',
            'Tonraq',
            'Hakoda',
            'Varrick',
            'Varrick',
            'Visola',
            'Princess Yue',
            'Yagoda',
            'Senna',
            'Senna',
            'Bato',
            'Bato',
            'Gran-Gran Kanna',
            'Tashi',
            'Korra',
        ]
    },
    {
        'name': 'Stone Cold Killers',
        'cards': [
            'Iroh II',
            'Iroh II',
            'Taqukaq',
            'Taqukaq',
            'Huu',
            'Naga',
            'Naga',
            'Sokka',
            'Sokka',
            'Mai',
            'Ming-Hua',
            'Ming-Hua',
            'June',
            'Master Pakku',
            'Master Pakku',
            'Yon Rha',
            'Yon Rha',
            'Piandao',
        ]
    },
    {
        'name': 'Capture the Flag',
        'cards': [
            'Tsemo',
            'Resistance Fighter',
            'Cabbage Man',
            'Teo',
            'Teo',
            'Kai',
            'Kai',
            'Lefty',
            'Yung',
            'Yung',
            'Izumi',
            'Joo Dee',
            'Council of Elders',
            'Champion Ming',
            'Champion Ming',
            'Professor Zei',
            'Queen Hou-Ting',
            'Bolin',
        ]
    },
]


BOT_DRAFT_DECKS = [
    {
        'name': 'Bot draft deck 1',
        'cards': [
            'Monk Gyatso',
            'Kai',
            'Appa',
            'Hakoda',
            'Oogi',
            'Hakoda',
            'Kai',
            'Appa',
            'Admiral Zhao',
            'Naga',
            'Tenzin',
            'Appa',
            'Admiral Zhao',
            'Bumi II',
            'Hakoda',
            'Oogi',
            'Riley',
            'Combustion Man',
        ]
    },
    {'name': 'Bot draft deck 2',
    'cards': ['Toph',
    'Fire Lord Ozai',
    'Combustion Man',
    'Fire Lord Ozai',
    'Iroh II',
    'Hakoda',
    'Hakoda',
    'Korra',
    'Mai',
    'Yon Rha',
    'Uncle Iroh',
    'Fire Lord Sozin',
    'Uncle Iroh',
    'Pabu',
    'Fire Lord Sozin',
    'Mai',
    'Mai',
    'Pabu']},
    {'name': 'Bot draft deck 3',
 'cards': ['Izumi',
  'Mother Kya',
  'Zaheer',
  'Master Pakku',
  'Mother Kya',
  'Katara',
  'Mother Kya',
  'Cabbage Man',
  'Sokka',
  'Hama',
  'Naga',
  'Ghazan',
  'Gran-Gran Kanna',
  'Zuko',
  'Zaheer',
  'Hama',
  'Kya',
  'Zuko']},
  {'name': 'Bot draft deck 4',
 'cards': ['Baatar Jr.',
  'La',
  'Zaheer',
  'Korra',
  'Oogi',
  'Zaheer',
  'Dai Li Agent',
  'La',
  'Fire Lord Sozin',
  'Uncle Iroh',
  'Zaheer',
  'Kyoshi',
  'Hakoda',
  'Dai Li Agent',
  'Kai',
  'Ghazan',
  'Kai',
  'Appa']},
  {'name': 'Bot draft deck 5',
  'cards': ['Yangchen',
  'Roku',
  'Aang',
  'Cabbage Man',
  'Tonraq',
  'Hiroshi',
  'Appa',
  'Aang',
  'Kuvira',
  'Zaheer',
  'Korra',
  'Aang',
  'Fire Lord Sozin',
  'Opal',
  'Zaheer',
  'Kyoshi',
  'Korra',
  'Momo']},
{'name': 'Bot draft deck 6',
 'cards': ['Jinora',
  'Aang',
  'Uncle Iroh',
  'Zuko',
  'Momo',
  'Hakoda',
  'Katara',
  'Suyin',
  'Opal',
  'Opal',
  'Aang',
  'Gran-Gran Kanna',
  'Korra',
  'Yangchen',
  'Suyin',
  'Lin',
  'Pabu',
  'Monk Gyatso']}  
]


def create_common_decks():
    with SessionLocal() as sess:
        for deck in COMMON_DECKS:
            if not sess.query(exists().where(DbDeck.name == deck['name']).where(DbDeck.username == COMMON_DECK_USERNAME)).scalar():
                add_db_deck(sess, deck['cards'], COMMON_DECK_USERNAME, deck['name'], None)

        for deck in BOT_DRAFT_DECKS:
            if not sess.query(exists().where(DbDeck.name == deck['name']).where(DbDeck.username == BOT_DECK_USERNAME)).scalar():
                add_db_deck(sess, deck['cards'], BOT_DECK_USERNAME, deck['name'], None)
