"""Add game_info column to game_state_records

Revision ID: 21d23b76b833
Revises: 2b710f8fbd0b
Create Date: 2023-11-01 17:29:42.442072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21d23b76b833'
down_revision = '2b710f8fbd0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_state_records', sa.Column('game_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, none_as_null=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_state_records', 'game_info')
    # ### end Alembic commands ###
