"""Add is_bot_draft_deck column to db_decks

Revision ID: 2b710f8fbd0b
Revises: 37eb9a5b135c
Create Date: 2023-11-01 13:35:07.379346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b710f8fbd0b'
down_revision = '37eb9a5b135c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_decks', sa.Column('is_bot_draft_deck', sa.Boolean(), server_default='f', nullable=False))
    op.create_index('db_decks_idx_is_bot_draft_deck_created_at', 'db_decks', ['is_bot_draft_deck', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('db_decks_idx_is_bot_draft_deck_created_at', table_name='db_decks')
    op.drop_column('db_decks', 'is_bot_draft_deck')
    # ### end Alembic commands ###
