"""Add unique_draft_identifier to db_decks

Revision ID: 37eb9a5b135c
Revises: ab4dd38e8a09
Create Date: 2023-11-01 12:53:10.073766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eb9a5b135c'
down_revision = 'ab4dd38e8a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_decks', sa.Column('unique_draft_identifier', sa.String(), nullable=True))
    op.add_column('db_decks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_db_decks_created_at'), 'db_decks', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_decks_unique_draft_identifier'), 'db_decks', ['unique_draft_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_decks_unique_draft_identifier'), table_name='db_decks')
    op.drop_index(op.f('ix_db_decks_created_at'), table_name='db_decks')
    op.drop_column('db_decks', 'created_at')
    op.drop_column('db_decks', 'unique_draft_identifier')
    # ### end Alembic commands ###
