"""Player and card outcomes

Revision ID: 4028c8c002f0
Revises: 68ae538b8c39
Create Date: 2023-10-30 15:08:46.213129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4028c8c002f0'
down_revision = '68ae538b8c39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['db_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('card_outcomes_idx_card_win_game_id', 'card_outcomes', ['card', 'win', 'game_id'], unique=False)
    op.create_index('card_outcomes_idx_game_id_card', 'card_outcomes', ['game_id', 'card'], unique=False)
    op.create_index(op.f('ix_card_outcomes_created_at'), 'card_outcomes', ['created_at'], unique=False)
    op.create_table('player_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_num', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['db_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_outcomes_created_at'), 'player_outcomes', ['created_at'], unique=False)
    op.create_index('player_outcomes_idx_game_id_username', 'player_outcomes', ['game_id', 'username'], unique=False)
    op.create_index('player_outcomes_idx_username_win_game_id', 'player_outcomes', ['username', 'win', 'game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('player_outcomes_idx_username_win_game_id', table_name='player_outcomes')
    op.drop_index('player_outcomes_idx_game_id_username', table_name='player_outcomes')
    op.drop_index(op.f('ix_player_outcomes_created_at'), table_name='player_outcomes')
    op.drop_table('player_outcomes')
    op.drop_index(op.f('ix_card_outcomes_created_at'), table_name='card_outcomes')
    op.drop_index('card_outcomes_idx_game_id_card', table_name='card_outcomes')
    op.drop_index('card_outcomes_idx_card_win_game_id', table_name='card_outcomes')
    op.drop_table('card_outcomes')
    # ### end Alembic commands ###
