"""Add db_cards

Revision ID: 5a1eea9932e6
Revises: fa6e4a9e21d8
Create Date: 2023-10-09 15:32:38.982430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1eea9932e6'
down_revision = 'fa6e4a9e21d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deck_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['db_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('db_cards_idx_deck_name', 'db_cards', ['deck_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('db_cards_idx_deck_name', table_name='db_cards')
    op.drop_table('db_cards')
    # ### end Alembic commands ###
