"""Add unique_draft_identifier column to draft_picks

Revision ID: 62f3d9fe2d44
Revises: 7b377939d2ec
Create Date: 2023-10-29 18:45:28.234076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f3d9fe2d44'
down_revision = '7b377939d2ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_picks', sa.Column('unique_draft_identifier', sa.String(), nullable=True))
    op.create_index('draft_picks_username_unique_draft_identifier_pick_num', 'draft_picks', ['username', 'unique_draft_identifier', 'pick_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('draft_picks_username_unique_draft_identifier_pick_num', table_name='draft_picks')
    op.drop_column('draft_picks', 'unique_draft_identifier')
    # ### end Alembic commands ###
