"""Add created_at column to game_state_records

Revision ID: 68ae538b8c39
Revises: 62f3d9fe2d44
Create Date: 2023-10-29 18:59:00.338076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ae538b8c39'
down_revision = '62f3d9fe2d44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_state_records', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_game_state_records_created_at'), 'game_state_records', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_state_records_created_at'), table_name='game_state_records')
    op.drop_column('game_state_records', 'created_at')
    # ### end Alembic commands ###
