"""Add draft choices

Revision ID: 7b377939d2ec
Revises: e3e415886f6c
Create Date: 2023-10-29 18:29:58.006869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b377939d2ec'
down_revision = 'e3e415886f6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_pick_id', sa.Integer(), nullable=True),
    sa.Column('card', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('picked', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['draft_pick_id'], ['draft_picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('draft_choices_idx_card_picked_created_at', 'draft_choices', ['card', 'picked', 'created_at'], unique=False)
    op.create_index('draft_choices_idx_draft_pick_id_created_at', 'draft_choices', ['draft_pick_id', 'created_at'], unique=False)
    op.create_index('draft_choices_idx_picked_created_at', 'draft_choices', ['picked', 'created_at'], unique=False)
    op.create_index(op.f('ix_draft_choices_created_at'), 'draft_choices', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_choices_created_at'), table_name='draft_choices')
    op.drop_index('draft_choices_idx_picked_created_at', table_name='draft_choices')
    op.drop_index('draft_choices_idx_draft_pick_id_created_at', table_name='draft_choices')
    op.drop_index('draft_choices_idx_card_picked_created_at', table_name='draft_choices')
    op.drop_table('draft_choices')
    # ### end Alembic commands ###
