"""Add DbGames

Revision ID: 8c8b3ba150cf
Revises: 5a1eea9932e6
Create Date: 2023-10-17 15:41:46.654478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8b3ba150cf'
down_revision = '5a1eea9932e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_0_username', sa.String(), nullable=True),
    sa.Column('player_1_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('db_games_idx_player_0_username_created_at', 'db_games', ['player_0_username', 'created_at'], unique=False)
    op.create_index('db_games_idx_player_1_username_created_at', 'db_games', ['player_1_username', 'created_at'], unique=False)
    op.create_index(op.f('ix_db_games_created_at'), 'db_games', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_games_created_at'), table_name='db_games')
    op.drop_index('db_games_idx_player_1_username_created_at', table_name='db_games')
    op.drop_index('db_games_idx_player_0_username_created_at', table_name='db_games')
    op.drop_table('db_games')
    # ### end Alembic commands ###
