"""Add game_state_records

Revision ID: 94bbea33d296
Revises: c3237ea3d20b
Create Date: 2023-10-26 01:53:13.864864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94bbea33d296'
down_revision = 'c3237ea3d20b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_state_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('player_0_username', sa.String(), nullable=True),
    sa.Column('player_1_username', sa.String(), nullable=True),
    sa.Column('game_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['db_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('game_state_records_idx_game_id_turn_number', 'game_state_records', ['game_id', 'turn'], unique=False)
    op.create_index('game_state_records_idx_player_0_username_game_id_turn_number', 'game_state_records', ['player_0_username', 'game_id', 'turn'], unique=False)
    op.create_index('game_state_records_idx_player_1_username_game_id_turn_number', 'game_state_records', ['player_1_username', 'game_id', 'turn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('game_state_records_idx_player_1_username_game_id_turn_number', table_name='game_state_records')
    op.drop_index('game_state_records_idx_player_0_username_game_id_turn_number', table_name='game_state_records')
    op.drop_index('game_state_records_idx_game_id_turn_number', table_name='game_state_records')
    op.drop_table('game_state_records')
    # ### end Alembic commands ###
