"""Rematch column to db_games

Revision ID: c3237ea3d20b
Revises: 8c8b3ba150cf
Create Date: 2023-10-25 15:16:55.982595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3237ea3d20b'
down_revision = '8c8b3ba150cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_games', sa.Column('rematch', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_games', 'rematch')
    # ### end Alembic commands ###
