"""Add draft picks

Revision ID: e3e415886f6c
Revises: 94bbea33d296
Create Date: 2023-10-29 18:29:35.082547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e415886f6c'
down_revision = '94bbea33d296'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('selected_draft_choice_id', sa.Integer(), nullable=True),
    sa.Column('pick_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('draft_picks_idx_username_created_at', 'draft_picks', ['username', 'created_at'], unique=False)
    op.create_index(op.f('ix_draft_picks_created_at'), 'draft_picks', ['created_at'], unique=False)
    op.create_index(op.f('ix_draft_picks_selected_draft_choice_id'), 'draft_picks', ['selected_draft_choice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_picks_selected_draft_choice_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_created_at'), table_name='draft_picks')
    op.drop_index('draft_picks_idx_username_created_at', table_name='draft_picks')
    op.drop_table('draft_picks')
    # ### end Alembic commands ###
