"""Add db_decks

Revision ID: fa6e4a9e21d8
Revises: 
Create Date: 2023-10-09 15:32:13.523231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6e4a9e21d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('associated_lane_reward_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('db_decks_idx_username_name', 'db_decks', ['username', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('db_decks_idx_username_name', table_name='db_decks')
    op.drop_table('db_decks')
    # ### end Alembic commands ###
